baseURL: "https://cristiansuarez.dev"
title: Cristian Suarez Dev Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Cristian Suarez Dev Blog
  description: "Blog dónde encontrarás artículos sobre múltiples temáticas que me resultan interesantes, sobre todo relacionadas con la informática."
  keywords: [ Blog, Portfolio ]
  author: "Cristian Suarez Dev"
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: true
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hola \U0001F44B"
    Content: Bienvenido a mi blog dónde encontrarás artículos sobre múltiples temáticas que me resultan interesantes, sobre todo relacionadas con la informática.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/criskrus995"
    #    - name: stackoverflow
    #      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/CrisKrus"
    - name: youtube
      url: "https://www.youtube.com/channel/UCqUyayArNENzh6kG0QldTXw/featured"
    - name: instagram
      url: "https://www.instagram.com/cristian_suarez_dev/"
    - name: buymeacoffee
      url: "https://www.buymeacoffee.com/cristianSuarez"
    - name: linkedin
      url: "https://www.linkedin.com/in/cristian-suarez-vera/"
    # - name: paypal
    #   url: ""
    # - name: telegram
    #   url: ""
    # - name: twitch
    #   url: ""
    # - name: discord
    #   url: ""

  analytics:
    google:
      SiteVerificationTag: "G-XJEZMMFYBD"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/CrisKrus/cristiansuarez.dev/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]
menu:
  main:
    - identifier: About
      name: About
      url: /about/
      weight: 5
    - identifier: charlas
      name: Charlas
      url: /talks/
      weight: 10
    - identifier: categories
      name: Categorias
      url: /categories/
      weight: 20
    - identifier: archivo
      name: Archivo
      url: /archive/
      weight: 30
#    - identifier: buscar
#      name: buscar
#      url: /search/
#      weight: 99
    #    - identifier: tags
    #      name: tags
    #      url: /tags/
    #      weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
